### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by arokettu** [vstebunov/vstebunov.github.io#1]
У тебя RSS поломался )

**Comment by arokettu** [comment]
Починился

**Comment by vstebunov** [comment]
> Починился

вау меня читают!

**Comment by arokettu** [comment]
axax. кстати, я так понял, что ты генеришь сайт своим скриптом, а почему бы не заюзать движок, тот же jekyll? та же статика, тот же маркдаун, тока имхо в разы удобнее

**Comment by vstebunov** [comment]
а в чем удобство?

**Comment by arokettu** [comment]
Ну например, если я правильно понял, у тебя в прошлый раз сфейлилась генерация RSS и ты не заметил :) полноценный продукт такого себе все же не позволит - или сгенерит или крашнется

Ну и свистелки - это уж надо или нет, там, автоапдейт ссылок если у тебя структура в исходниках и в html разная, темки, категории, сео теги, разные форматы постов, сборка фронтенда, обработка картинок - я некоторые фичи юзаю
